<?php

namespace webstik\telegramNotifications\controllers;

use Exception;
use Longman\TelegramBot\Request;
use webstik\telegramNotifications\Telegram;
use Yii;
use webstik\telegramNotifications\models\TelegramSettings;
use Longman\TelegramBot\Exception\TelegramException;


class TelegramManagerController extends \yii\web\Controller
{
    public function actionIndex()
    {
        $telegram_setting = TelegramSettings::getSettings();
        try {
            $telegram = new Telegram($telegram_setting->token, $telegram_setting->bot_username);

            $telegram->handle();
        } catch (Exception $e) {
            file_put_contents('telega.log', print_r($e->getMessage(), true)."\n", FILE_APPEND);
        }

        return;
    }

    public function beforeAction($action)
    {
        Yii::$app->controller->enableCsrfValidation = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}
